package vista;


import bean.Cliente;
import bean.Vehiculo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.arreglo_Cliente;
import java.awt.Toolkit;

public class JFCliente extends javax.swing.JFrame {

    arreglo_Cliente listaCliente = new arreglo_Cliente();

    DefaultTableModel modelo;

    public JFCliente() {
        initComponents();
        modelo = (DefaultTableModel) tblListaCliente.getModel();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApeP = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtApeM = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtLicencia = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtCodigoBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaCliente = new javax.swing.JTable();
        btnEliminarCliente = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtNombreM = new javax.swing.JTextField();
        txtApeMaternoM = new javax.swing.JTextField();
        txtEdadM = new javax.swing.JTextField();
        txtTelefonoM = new javax.swing.JTextField();
        txtCodigoM = new javax.swing.JTextField();
        txtApePaternoM = new javax.swing.JTextField();
        txtDniM = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtLicenciaM = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnBorrarM = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnBuscarM = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtDireccionM = new javax.swing.JTextField();
        btnGuardarM = new javax.swing.JButton();

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("REGISTRAR");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CODIGO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 102, 83, 24));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TELEFONO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 330, 83, 24));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("NOMBRE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 102, 83, 24));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("APE. MATERNO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 179, 136, 24));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("APE. PATERNO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 179, 146, 24));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("DNI");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 253, 83, 24));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("EDAD");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 253, 83, 24));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("DIRECCION");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 106, 24));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 137, 279, 36));

        txtApeP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApePKeyTyped(evt);
            }
        });
        jPanel1.add(txtApeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 209, 266, 38));

        txtEdad.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                txtEdadComponentHidden(evt);
            }
        });
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 283, 266, 36));

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 360, 266, 33));

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 137, 266, 36));

        txtApeM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApeMKeyTyped(evt);
            }
        });
        jPanel1.add(txtApeM, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 209, 279, 38));

        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniKeyTyped(evt);
            }
        });
        jPanel1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 283, 279, 36));

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 279, 33));

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 51, 51));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 469, 140, 50));

        btnBorrar.setBackground(new java.awt.Color(0, 0, 0));
        btnBorrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 51, 51));
        btnBorrar.setText("LIMPIAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 469, 150, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("REGISTRAR CLIENTE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 20, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 711, -1));
        jPanel1.add(txtLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 210, 35));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("N°LICENCIA");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 108, -1));

        jTabbedPane1.addTab("REGISTRAR CLIENTE", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("CODIGO");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, 30));

        txtCodigoBuscar.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigoBuscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCodigoBuscar.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(txtCodigoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 110, 40));

        tblListaCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblListaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "APE.PATERNO", "APE.MATERNO", "EDAD", "DNI", "TELEFONO", "DIRECCION", "N°LICENCIA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListaCliente);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 122, 656, 393));

        btnEliminarCliente.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminarCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarCliente.setForeground(new java.awt.Color(255, 51, 51));
        btnEliminarCliente.setText("ELIMINAR");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, 50));

        btnListar.setBackground(new java.awt.Color(0, 0, 0));
        btnListar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 51, 51));
        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jPanel2.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 170, 50));

        jTabbedPane1.addTab("BUSCAR CLIENTE", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtNombreM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreMKeyTyped(evt);
            }
        });

        txtApeMaternoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApeMaternoMKeyTyped(evt);
            }
        });

        txtEdadM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadMKeyTyped(evt);
            }
        });

        txtTelefonoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoMActionPerformed(evt);
            }
        });
        txtTelefonoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoMKeyTyped(evt);
            }
        });

        txtCodigoM.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigoM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCodigoM.setForeground(new java.awt.Color(204, 0, 0));
        txtCodigoM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCodigoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoMKeyTyped(evt);
            }
        });

        txtApePaternoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApePaternoMKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("N°LICENCIA");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("CODIGO");

        btnBorrarM.setBackground(new java.awt.Color(0, 0, 0));
        btnBorrarM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBorrarM.setForeground(new java.awt.Color(255, 51, 51));
        btnBorrarM.setText("NUEVO");
        btnBorrarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarMActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("TELEFONO");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("NOMBRE");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("APE. MATERNO");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("APE. PATERNO");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("DNI");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("EDAD");

        btnBuscarM.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscarM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuscarM.setForeground(new java.awt.Color(255, 51, 51));
        btnBuscarM.setText("BUSCAR");
        btnBuscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Direccion");

        btnGuardarM.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardarM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGuardarM.setForeground(new java.awt.Color(255, 51, 51));
        btnGuardarM.setText("GUARDAR");
        btnGuardarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTelefonoM, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                        .addComponent(txtApeMaternoM))
                    .addComponent(txtNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDniM, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApePaternoM, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(txtEdadM, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicenciaM, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtDireccionM))
                .addGap(61, 61, 61))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(txtCodigoM, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnBuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnGuardarM)
                        .addGap(58, 58, 58)
                        .addComponent(btnBorrarM, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarM, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(txtCodigoM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApePaternoM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApeMaternoM, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdadM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDniM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicenciaM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelefonoM, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(txtDireccionM))
                        .addGap(32, 138, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBorrarM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))))
        );

        jTabbedPane1.addTab("MODIFICAR CLIENTE", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtTelefonoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoMActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        guardar();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMActionPerformed
        buscarModificar();
    }//GEN-LAST:event_btnBuscarMActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnBorrarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarMActionPerformed
        borrar();
    }//GEN-LAST:event_btnBorrarMActionPerformed

    private void btnGuardarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMActionPerformed
        actualizar();
    }//GEN-LAST:event_btnGuardarMActionPerformed

    private void tblListaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaClienteMouseClicked
        if(evt.getClickCount()==1){
            enviarCodigo();
            
        }
        if (evt.getClickCount() == 2) {
            enviarCliente();
        }
        
        
        
        
    }//GEN-LAST:event_tblListaClienteMouseClicked

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {

        } else {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtApePKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApePKeyTyped
               Character c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        
    }//GEN-LAST:event_txtApePKeyTyped

    private void txtApeMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeMKeyTyped
                Character c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        
    }//GEN-LAST:event_txtApeMKeyTyped

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
                char c = evt.getKeyChar();
        if (Character.isDigit(c)) {

        } else {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }       
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyTyped
      
    }//GEN-LAST:event_txtDniKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
                        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {

        } else {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }  
       
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
         
        
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtEdadComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtEdadComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadComponentHidden

    private void txtCodigoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoMKeyTyped
           char c = evt.getKeyChar();
        if (Character.isDigit(c)) {

        } else {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtCodigoMKeyTyped

    private void txtNombreMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreMKeyTyped
                Character c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }     
    }//GEN-LAST:event_txtNombreMKeyTyped

    private void txtApePaternoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApePaternoMKeyTyped
                Character c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtApePaternoMKeyTyped

    private void txtApeMaternoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeMaternoMKeyTyped
           Character c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtApeMaternoMKeyTyped

    private void txtEdadMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadMKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {

        } else {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtEdadMKeyTyped

    private void txtTelefonoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoMKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {

        } else {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtTelefonoMKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrarM;
    private javax.swing.JButton btnBuscarM;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnGuardarM;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    public static javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblListaCliente;
    private javax.swing.JTextField txtApeM;
    private javax.swing.JTextField txtApeMaternoM;
    private javax.swing.JTextField txtApeP;
    private javax.swing.JTextField txtApePaternoM;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoBuscar;
    private javax.swing.JTextField txtCodigoM;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccionM;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDniM;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEdadM;
    private javax.swing.JTextField txtLicencia;
    private javax.swing.JTextField txtLicenciaM;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreM;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoM;
    // End of variables declaration//GEN-END:variables

    private void guardar() {
       boolean validar = txtCodigo.getText().equals("") || txtNombre.getText().equals("") || txtApeP.getText().equals("")||
              txtApeM.getText().equals("") || txtEdad.getText().equals("") || txtDni.getText().equals("")||
              txtTelefono.getText().equals("")|| txtDireccion.getText().equals("")|| txtLicencia.getText().equals(""); 
        if (!validar) {
        try {
            Cliente p= new Cliente(getCodigo(), getNombre(),getApePaterno(),getApeMaterno(),getEdad(),getDni(),
                    getTelefono(),getDireccion(),getLicencia());
            String respuesta = listaCliente.adicionar(p);
            listaCliente.grabar();
            JOptionPane.showMessageDialog(null, respuesta);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());
            limpiar();
        }  
    }else{
            JOptionPane.showMessageDialog(null, "Rellene todos los campos");
        }
    }
    private int getCodigo(){
        return Integer.parseInt(txtCodigo.getText());
    }
    
    private String getNombre(){
        return txtNombre.getText();
    }
    
    private String getApePaterno(){
        return txtApeP.getText();
    }
    private String getApeMaterno(){
    return txtApeM.getText();
    }
    private int getEdad(){
        return Integer.parseInt(txtEdad.getText());
    }    
    private int getDni(){
        return Integer.parseInt(txtDni.getText());
    }   
    
    private int getTelefono(){
        return Integer.parseInt(txtTelefono.getText());    
    }
    private String getDireccion(){
       return txtDireccion.getText();   
    }   
    private String getLicencia(){
       return txtLicencia.getText();  
    }
    private void limpiar() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtApeP.setText("");
        txtApeM.setText("");
        txtEdad.setText("");
        txtDni.setText("");
        txtLicencia.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
        txtCodigo.requestFocus();
    }
    private void listar() {
        //limpiar la tabla
        int filas = tblListaCliente.getRowCount();
        for(int i=0; i<filas; i++)
                modelo.removeRow(0);  
    
         //agregar la lista a la tabla
       if(listaCliente.totalCliente()>0)
       for(int i=0; i<listaCliente.totalCliente(); i++){
                modelo.addRow(new Object[]{
                    listaCliente.obtener(i).getCodigo(),
                    listaCliente.obtener(i).getNombre(),
                    listaCliente.obtener(i).getApePaterno(),
                    listaCliente.obtener(i).getApeMaterno(),
                    listaCliente.obtener(i).getEdad(),
                    listaCliente.obtener(i).getDni(),
                    listaCliente.obtener(i).getTelefono(),
                    listaCliente.obtener(i).getDireccion(),
                    listaCliente.obtener(i).getLicencia(),
                    listaCliente.obtener(i).getDni()});
            }
        else JOptionPane.showMessageDialog(null, "No hay Clientes para mostrar");
    }  

    private void mostrarAlumno(Cliente p) {
        txtNombreM.setText(p.getNombre());
        txtApePaternoM.setText(p.getApePaterno());
        txtApeMaternoM.setText(p.getApeMaterno());
        txtEdadM.setText(String.valueOf(p.getEdad()));
        txtDniM.setText(String.valueOf(p.getDni()));
        txtLicenciaM.setText(String.valueOf(p.getLicencia()));
        txtTelefonoM.setText(String.valueOf(p.getTelefono()));
        txtDireccionM.setText(String.valueOf(p.getDireccion()));
        
    }  
     private void actualizar() {
       boolean validar = txtCodigoM.getText().equals("") || txtNombreM.getText().equals("") || txtApePaternoM.getText().equals("")||
              txtApeMaternoM.getText().equals("") || txtEdadM.getText().equals("") || txtDniM.getText().equals("")||
              txtTelefonoM.getText().equals("")|| txtDireccionM.getText().equals("")|| txtLicenciaM.getText().equals(""); 
        if (!validar) { 
            try{
                Cliente p = new Cliente(getCodigoM(), getNombreM(),getApePaternoM()
                    ,getApeMaternoM(),getEdadM(),getDniM(),
                    getTelefonoM(),getDireccionM(),
                    getLicenciaM());
                 listaCliente.actualizar(p);
                listaCliente.grabar();
            JOptionPane.showMessageDialog(null, "Actualización realizada con éxito");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No cambie el código");
        }
     }else{
            JOptionPane.showMessageDialog(null,"Rellene todos los campos");
        }
     }
    private int getCodigoM() {
        return Integer.parseInt(txtCodigoM.getText());
    }    
    private String getNombreM(){
    return txtNombreM.getText();
    } 
    private String getApePaternoM(){
    return txtApePaternoM.getText();   
    }
    private String getApeMaternoM(){
    return txtApeMaternoM.getText();   
    }
    private int getEdadM() {
        return Integer.parseInt(txtEdadM.getText());   
    }
    private int getDniM() {
        return Integer.parseInt(txtDniM.getText());   
    }
    private int getTelefonoM() {
        return Integer.parseInt(txtTelefonoM.getText());     
    }
    private String getDireccionM(){
    return txtDireccionM.getText();   
    } 
    private String getLicenciaM() {
    return txtLicenciaM.getText();       
    }
      
    private void eliminar() {
        try{
            Cliente p = null;
            p = listaCliente.buscar(getCodigoBuscar());
            listaCliente.grabar();
            listaCliente.eliminar(p);
            JOptionPane.showMessageDialog(null, "Eliminación correctamente");
            listar();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error no se pudo Eliminar: "+e.toString());     
        }
    }
    private int getCodigoBuscar() {
        return Integer.parseInt(txtCodigoBuscar.getText());
    }    

    private void buscarModificar() {
        try{
            Cliente p = null;
            p = listaCliente.buscar(getCodigoM());
            mostrarAlumno(p);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "El código no existe");
        }
    }

    private void borrar() {
        txtCodigoM.setText("");
        txtNombreM.setText("");
        txtApePaternoM.setText("");
        txtApeMaternoM.setText("");
        txtEdadM.setText("");
        txtDniM.setText("");
        txtLicenciaM.setText("");
        txtTelefonoM.setText("");
        txtDireccionM.setText("");
        txtCodigoM.requestFocus();
    }
    
     private void enviarCodigo() {
        int fila= tblListaCliente.getSelectedRow();
        if(fila>=0){
            int pos = (int)tblListaCliente.getValueAt(fila, 0);
            Cliente v = listaCliente.buscar(pos);
            txtCodigoBuscar.setText(String.valueOf(v.getCodigo()));
        }
    }
     
     private void enviarCliente(){
         int fila = tblListaCliente.getSelectedRow();
        if (fila >= 0) {
            int pos = (int) tblListaCliente.getValueAt(fila, 0);
            Cliente c = listaCliente.buscar(pos);
            JFPrincipal.lblNombreCli.setText(c.getNombre()+ " " + c.getApePaterno());
            JFPrincipal.lblDniCli.setText(String.valueOf(c.getDni()));
            JFPrincipal.cli = c;
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona una fila de la Tabla para enviar los datos");
        }
     }
   
}
